#' Print Method for Model Fit Indices
#'
#' @description
#' `print.model_fit` is a custom print method for objects generated by the [`model_fit`] function.
#' It formats the output table using [`insight::format_table`] and exports it using [`insight::export_table`].
#'
#' @param x An object of class `model_fit`, typically created by the [`model_fit`] function.
#' @param digits Number of digits for rounding numeric values. Default is 3.
#' @param p_digits Number of digits for rounding p-values. Default is 3.
#' @param format Output format for the table. Can be "text", "markdown" (or "md"), or "html". Default is "text".
#' @param align Alignment for the table when the format is "text" or "markdown". Options include "left", "right",
#'  "center", and "firstleft". Default is "firstleft". For more information on alignment options, consult
#'   the documentation for [`insight::export_table`].
#' @param ... Additional arguments passed to formatting functions.
#'   If `format = "text"` or `format = "markdown"` they are passed to [`insight::export_table`].
#'   If `format = "html"` these arguments are passed to [`tinytable::tt`].
#'
#' @return The formatted table is printed to the console.
#' @examples
#' if (requireNamespace("lavaan", quietly = TRUE)) {
#'   library(lavaan)
#'   library(psymetrics)
#'
#'   model <- 'visual  =~ x1 + x2 + x3
#'           textual =~ x4 + x5 + x6
#'           speed   =~ x7 + x8 + x9'
#'
#'   fit <- cfa(model, data = HolzingerSwineford1939,
#'              estimator = "MLR")
#'   result <- model_fit(fit)
#'   result
#'   print(result, format = "html")
#' } else {
#'   message("Please install 'lavaan' to run this example.")
#' }
#'
#' @export
print.model_fit <- function(x, digits = 3, p_digits = 3,
                            format = "text", align = "firstleft",
                            ...) {

  formatted_table <- prepare_table(x,
                                   columns_to_format = c("NOBS", "NPAR", "Chi2_df"),
                                   digits = digits,
                                   ci_digits = digits,
                                   p_digits = p_digits)

  return(
    print_format(formatted_table, format = format,
                 align = align, ...)
  )

  invisible(x)
}
