#' Print Method for compare_model_fit Objects
#'
#' @description This function provides a custom print method for objects of class
#' `compare_model_fit`, which are generated by the `compare_model_fit()` function.
#' It formats and displays the comparison of model fit indices in a clear and
#' readable table.
#'
#' @param x An object of class `compare_model_fit`, created by the `compare_model_fit()` function.
#' @param digits Integer. Number of digits to use for displaying numeric values. Defaults to 3.
#' @param p_digits Integer. Number of digits to use for displaying p-values. Defaults to 3.
#' @param format Character. The format in which to print the table. Options are `"text"`, `"markdown"`, or `"html"`. Defaults to `"text"`.
#' @param ... Additional arguments passed to formatting functions.
#'   If `format = "text"` or `format = "markdown"` they are passed to `insight::export_table`.
#'   If `format = "html"` these arguments are passed to `tinytable::tt`.
#'
#' @return Invisibly returns the `compare_model_fit` object. The main purpose of this function is to print the formatted comparison table.
#' @export
#'
#' @examples
#' library(psymetrics)
#' library(lavaan)
#'
#' model1 <- 'visual  =~ x1 + x2 + x3
#'            textual =~ x4 + x5 + x6'
#' fit1 <- cfa(model1, data = HolzingerSwineford1939, estimator = "ML")
#' fit2 <- cfa(model1, data = HolzingerSwineford1939, estimator = "MLR")
#' comparison <- compare_model_fit(fit1, fit2)
#' comparison
#' print(comparison, format = "html")
print.compare_model_fit <- function(x, digits = 3, p_digits = 3,
                                    format = "text", align = "firstleft",
                                    ...) {

  formatted_table <- prepare_table(x,
                                   columns_to_format = c("NOBS", "NPAR", "Chi2_df"),
                                   digits = digits,
                                   ci_digits = digits,
                                   p_digits = p_digits)

  return(
    print_format(formatted_table, format = format,
                 align = align, ...)
  )

  invisible(x)
}
