#' Print Method for Model Fit Indices
#'
#' @description
#' `print.model_fit` is a custom print method for objects generated by the `model_fit` function.
#' It formats the output table using `insight::format_table` and exports it using `insight::export_table`.
#'
#' @param x An object of class `model_fit`, typically created by the `model_fit` function.
#' @param digits Number of digits for rounding numeric values. Default is 3.
#' @param p_digits Number of digits for rounding p-values. Default is 3.
#' @param format Output format for the table. Can be "text", "markdown" (or "md"), or "html". Default is "text".
#' @param ... Additional arguments passed to `insight::export_table`.
#' @return The formatted table is printed to the console.
#' @method print model_fit
#' @export
#' @examples
#' \dontrun{
#' library(lavaan)
#' model <- 'visual  =~ x1 + x2 + x3
#'           textual =~ x4 + x5 + x6
#'           speed   =~ x7 + x8 + x9'
#' fit <- cfa(model, data = HolzingerSwineford1939, estimator = "MLR")
#' result <- model_fit(fit)
#' print(result)
#' }
print.model_fit <- function(x, digits = 3, p_digits = 3, format = "text", ...) {
  formatted_table <- insight::format_table(x, digits = digits, p_digits = p_digits)

  cat(
    insight::export_table(
      x = formatted_table,
      digits = digits,
      format = format,
      ...
    )
  )

  invisible(x)
}
